env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  requireConfigFile: false
  babelOptions:
    plugins:
      - "@babel/plugin-proposal-class-properties"
      - "@babel/plugin-syntax-class-properties"
rules: { quotes: [2, "single", "avoid-escape"] }
parser: "@babel/eslint-parser"
plugins:
  - "@babel"
