version: '3.3'
services:
  svn:
    image: kuchida1981/subversion-httpd
    environment:
      SVN_DEFAULT_USER: ${SVN_USER}
      SVN_DEFAULT_USER_PASSWD: ${SVN_PASS}
      SVN_DEFAULT_REPOSITORY: gb-sandbox
    ports:
      - 10080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
